/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import logica.UtilsDB;

/**
 *
 * @author Nicolas
 */
public class EditarDatosCantante extends javax.swing.JFrame {

    public static String nombreC;

    Fondo fondo = new Fondo();

    /**
     * Creates new form AgregarCantante
     */
    public EditarDatosCantante() {

        this.setContentPane(fondo);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        txtfIngresarNombre1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtfIngresarNombreNuevo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtfDiscoConMasVentasNuevo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtfNuevoNumeroTotalVentas = new javax.swing.JTextField();
        btnEnviarEdicionCantante = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Nombre");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(717, 485));
        setMinimumSize(new java.awt.Dimension(717, 485));
        setPreferredSize(new java.awt.Dimension(717, 485));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Harlow Solid Italic", 0, 64)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 102));
        jLabel1.setText(" Editar Cantante ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        txtfIngresarNombreNuevo.setBackground(new java.awt.Color(102, 0, 102));
        txtfIngresarNombreNuevo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfIngresarNombreNuevo.setForeground(new java.awt.Color(255, 255, 255));
        txtfIngresarNombreNuevo.setBorder(null);
        txtfIngresarNombreNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfIngresarNombreNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(txtfIngresarNombreNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 210, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nuevo disco con mas ventas");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, -1, -1));

        txtfDiscoConMasVentasNuevo.setBackground(new java.awt.Color(102, 0, 102));
        txtfDiscoConMasVentasNuevo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfDiscoConMasVentasNuevo.setForeground(new java.awt.Color(255, 255, 255));
        txtfDiscoConMasVentasNuevo.setBorder(null);
        getContentPane().add(txtfDiscoConMasVentasNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 210, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nuevo numero total de ventas");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, -1, -1));

        txtfNuevoNumeroTotalVentas.setBackground(new java.awt.Color(102, 0, 102));
        txtfNuevoNumeroTotalVentas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfNuevoNumeroTotalVentas.setForeground(new java.awt.Color(255, 255, 255));
        txtfNuevoNumeroTotalVentas.setBorder(null);
        getContentPane().add(txtfNuevoNumeroTotalVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 210, 40));

        btnEnviarEdicionCantante.setBackground(new java.awt.Color(102, 0, 102));
        btnEnviarEdicionCantante.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEnviarEdicionCantante.setForeground(new java.awt.Color(255, 255, 255));
        btnEnviarEdicionCantante.setText("Editar");
        btnEnviarEdicionCantante.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnEnviarEdicionCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarEdicionCantanteActionPerformed(evt);
            }
        });
        getContentPane().add(btnEnviarEdicionCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, 170, 50));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nuevo nombre");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarEdicionCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarEdicionCantanteActionPerformed

        try {

            UtilsDB.editarCantante(nombreC, txtfIngresarNombreNuevo.getText(), txtfDiscoConMasVentasNuevo.getText(), txtfNuevoNumeroTotalVentas.getText());

            this.dispose();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ingrese bien los datos.");
            this.dispose();

        }

    }//GEN-LAST:event_btnEnviarEdicionCantanteActionPerformed

    public JTextField getTxtfDiscoConMasVentasNuevo() {
        return txtfDiscoConMasVentasNuevo;
    }

    public void setTxtfDiscoConMasVentasNuevo(JTextField txtfDiscoConMasVentasNuevo) {
        this.txtfDiscoConMasVentasNuevo = txtfDiscoConMasVentasNuevo;
    }

    public JTextField getTxtfIngresarNombre1() {
        return txtfIngresarNombre1;
    }

    public void setTxtfIngresarNombre1(JTextField txtfIngresarNombre1) {
        this.txtfIngresarNombre1 = txtfIngresarNombre1;
    }

    public JTextField getTxtfIngresarNombreNuevo() {
        return txtfIngresarNombreNuevo;
    }

    public JTextField getTxtfNuevoNumeroTotalVentas() {
        return txtfNuevoNumeroTotalVentas;
    }

    public void setTxtfNuevoNumeroTotalVentas(JTextField txtfNuevoNumeroTotalVentas) {
        this.txtfNuevoNumeroTotalVentas = txtfNuevoNumeroTotalVentas;
    }

    public void setTxtfTotalVentasNuevo(JTextField txtfTotalVentasNuevo) {
        this.txtfNuevoNumeroTotalVentas = txtfTotalVentasNuevo;
    }


    private void txtfIngresarNombreNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfIngresarNombreNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfIngresarNombreNuevoActionPerformed

    class Fondo extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/imagenes/imagenFondo.jpg")).getImage();

            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);

            setOpaque(false);

            super.paint(g);

        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviarEdicionCantante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtfDiscoConMasVentasNuevo;
    private javax.swing.JTextField txtfIngresarNombre1;
    private javax.swing.JTextField txtfIngresarNombreNuevo;
    private javax.swing.JTextField txtfNuevoNumeroTotalVentas;
    // End of variables declaration//GEN-END:variables
}
