/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import logica.UtilsDB;

/**
 *
 * @author Nicolas
 */
public class EliminarCantante extends javax.swing.JFrame {

    Fondo fondo = new Fondo();

    /**
     * Creates new form EliminarCantante
     */
    public EliminarCantante() {

        this.setContentPane(fondo);
        initComponents();
        UtilsDB.Conectar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtfIngresarNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtfnombreEliminarCantante = new javax.swing.JTextField();
        btnEliminarCantante = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre");

        txtfIngresarNombre.setBackground(new java.awt.Color(153, 153, 153));
        txtfIngresarNombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtfIngresarNombre.setForeground(new java.awt.Color(0, 0, 0));
        txtfIngresarNombre.setBorder(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(613, 294));
        setMinimumSize(new java.awt.Dimension(613, 294));
        setPreferredSize(new java.awt.Dimension(613, 294));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Harlow Solid Italic", 0, 54)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 102));
        jLabel1.setText(" Eliminar Cantante ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        txtfnombreEliminarCantante.setBackground(new java.awt.Color(102, 0, 102));
        txtfnombreEliminarCantante.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfnombreEliminarCantante.setForeground(new java.awt.Color(255, 255, 255));
        txtfnombreEliminarCantante.setBorder(null);
        txtfnombreEliminarCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfnombreEliminarCantanteActionPerformed(evt);
            }
        });
        getContentPane().add(txtfnombreEliminarCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 210, 40));

        btnEliminarCantante.setBackground(new java.awt.Color(102, 0, 102));
        btnEliminarCantante.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEliminarCantante.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarCantante.setText("Eliminar");
        btnEliminarCantante.setBorder(null);
        btnEliminarCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCantanteActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminarCantante, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 180, 50));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCantanteActionPerformed

        try {

            UtilsDB.eliminarCantante(txtfnombreEliminarCantante.getText());

            this.dispose();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ingrese los datos bien.");
            this.dispose();
        }


    }//GEN-LAST:event_btnEliminarCantanteActionPerformed

    private void txtfnombreEliminarCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfnombreEliminarCantanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfnombreEliminarCantanteActionPerformed

    public static void setTxtfnombreEliminarCantante(JTextField txtfnombreEliminarCantante) {
        EliminarCantante.txtfnombreEliminarCantante = txtfnombreEliminarCantante;
    }

    public static JTextField getTxtfnombreEliminarCantante() {
        return txtfnombreEliminarCantante;
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarCantante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtfIngresarNombre;
    public static javax.swing.JTextField txtfnombreEliminarCantante;
    // End of variables declaration//GEN-END:variables

    class Fondo extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/imagenes/imagenFondo.jpg")).getImage();

            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);

            setOpaque(false);

            super.paint(g);

        }

    }
}
